# Generated by Django 3.0 on 2019-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="aprooved",
            field=models.BooleanField(default=False),
        ),
    ]
