var child = [
  { 'dupe': false, 'type': 64, 'name': 'csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP', 'dir': 'c0', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed5cd },
  { 'dupe': false, 'type': 64, 'name': 'email=skipfish@example.com', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed5cd },
  { 'dupe': false, 'type': 64, 'name': 'first_name=John', 'dir': 'c2', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed5cd },
  { 'dupe': false, 'type': 64, 'name': 'last_name=Smith', 'dir': 'c3', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed5cd },
  { 'dupe': false, 'type': 64, 'name': 'password1=skipfish', 'dir': 'c4', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xffbd871a },
  { 'dupe': false, 'type': 64, 'name': 'password2=skipfish', 'dir': 'c5', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed5cd },
  { 'dupe': false, 'type': 64, 'name': 'username=Smith', 'dir': 'c6', 'linked': 5, 'url': 'http://127.0.0.1:8000/signup/ DATA:csrfmiddlewaretoken=EkgjEYhnyUf0s6GHJlwRX07HTVrDwI42FEfRljXNKG7FkwW4hIHJUYsDnvi05euP&username=Smith&first_name=John&last_name=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xffbd871a }
];
